"""
Django settings for btsbook project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dfjortzl(4y83$h9u^vv%ii#zc^w*w#3_k485ar^qpiym*$7a5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '192.168.8.199',
    'virginia-addressing-learning-routine.trycloudflare.com',
    'b427-37-161-174-237.ngrok-free.app',
    'becrazyordream.com',
    'www.becrazyordream.com',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'btsbook.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.stripe_public_key',
            ],
        },
    },
]

WSGI_APPLICATION = 'btsbook.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'basingerfelix17@gmail.com'
EMAIL_HOST_PASSWORD = 'ihmlemkgtxgvzaye'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

STRIPE_PUBLIC_KEY = "pk_test_51Qo59JIAOpbVd3mDewywB4BeR1kMOLMHSzIO7yQmnfmvFYdCJbxASpIsVEb0P2FK2iXSmtJ2dlCXF4qj0ahY8bIj00BBQjdNh6"
STRIPE_SECRET_KEY = "sk_test_51Qo59JIAOpbVd3mDHoor8eln90kxJkR5l2wUgAqZXZPdEoFnVsyeI9PEJAzP3Yf0NTcCTW78soir17MzgnRkkRej00FjYNEIOW"

LIQPAY_PUBLIC_KEY = 'sandbox_i49355397113'
LIQPAY_PRIVATE_KEY = 'sandbox_NWPmi6HgGGMFbzyDu8rdreIPgXMQOCSVr9v1Ru1J'

CSRF_TRUSTED_ORIGINS = [
    'https://wu-smart-alternatively-serial.trycloudflare.com',
    'https://www.liqpay.ua',
    'https://virginia-addressing-learning-routine.trycloudflare.com',
    'https://b427-37-161-174-237.ngrok-free.app',
]

CSRF_COOKIE_SECURE = True  # Установите True, если используете HTTPS
CSRF_COOKIE_HTTPONLY = False  # Разрешите доступ через JavaScript, если нужно
CSRF_USE_SESSIONS = False

SESSION_COOKIE_AGE = 3600  # Время жизни сессии (1 час)
SESSION_SAVE_EVERY_REQUEST = True  # Обновление сессии при каждом запросе

SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Хранение сессий в БД
SESSION_COOKIE_SECURE = False  # Если используете HTTPS
SESSION_COOKIE_SAMESITE = 'Lax'
