# Generated by Django 5.1.5 on 2025-02-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedtoken',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
