# Generated by Django 5.1.5 on 2025-02-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_processedtoken_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedtoken',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
