# Generated by Django 5.1.5 on 2025-02-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_processedtoken_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedtoken',
            name='is_processing',
            field=models.BooleanField(default=False),
        ),
    ]
